version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    healthcheck:
      test: curl -fs http://localhost:8000/healthz/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3